version: '3.9'

services:
  core-db:
    image: postgres:16-alpine
    container_name: core_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_db
    ports:
      - '5432:5432'
    volumes:
      - core_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  core-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core_service
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@core-db:5432/core_db
    ports:
      - '3001:3001'
    depends_on:
      core-db:
        condition: service_healthy

volumes:
  core_db_data:
